name: Deploy API Azure 01

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Build
      run: dotnet build AzureApi01/AzureApi01.sln --configuration Release

    - name: Publish
      run: dotnet publish AzureApi01/AzureApi01/AzureApi01.csproj -c Release -o ./publish

    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: azure-api-01
        publish-profile: ${{ secrets.DEPLOY_API_AZURE }}
        package: ./publish
